version: "3.7"

services:
  compalex:
    image: dlevsha/compalex
    container_name: compalex
    environment:
      - DATABASE_DRIVER=mysql
      - DATABASE_ENCODING=utf8
      - SAMPLE_DATA_LENGTH=100
      - DATABASE_DESCRIPTION_SECONDARY=Production database
# Credentials removed I hate Docker compose
    ports:
      - "8000:8000"